iconv -f windows-1251 -t UTF-8 ./data/in/che.txt > ./converted/che.txt
iconv -f windows-1251 -t UTF-8 ./data/in/detmir.txt > ./converted/detmir.txt
iconv -f windows-1251 -t UTF-8 ./data/in/disney.txt > ./converted/disney.txt
iconv -f windows-1251 -t UTF-8 ./data/in/dom.txt > ./converted/dom.txt
iconv -f windows-1251 -t UTF-8 ./data/in/domkino.txt > ./converted/domkino.txt
iconv -f windows-1251 -t UTF-8 ./data/in/drive.txt > ./converted/drive.txt
iconv -f windows-1251 -t UTF-8 ./data/in/dva.txt > ./converted/dva.txt
iconv -f windows-1251 -t UTF-8 ./data/in/explorer.txt > ./converted/explorer.txt
iconv -f windows-1251 -t UTF-8 ./data/in/foxlife.txt > ./converted/foxlife.txt
iconv -f windows-1251 -t UTF-8 ./data/in/friday.txt > ./converted/friday.txt
iconv -f windows-1251 -t UTF-8 ./data/in/history.txt > ./converted/history.txt
iconv -f windows-1251 -t UTF-8 ./data/in/jivi.txt > ./converted/jivi.txt
iconv -f windows-1251 -t UTF-8 ./data/in/kanal5.txt > ./converted/kanal5.txt
iconv -f windows-1251 -t UTF-8 ./data/in/karusel.txt > ./converted/karusel.txt
iconv -f windows-1251 -t UTF-8 ./data/in/kultura.txt > ./converted/kultura.txt
iconv -f windows-1251 -t UTF-8 ./data/in/match.txt > ./converted/match.txt
iconv -f windows-1251 -t UTF-8 ./data/in/mir.txt > ./converted/mir.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ngc.txt > ./converted/ngc.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ntv.txt > ./converted/ntv.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ohota.txt > ./converted/ohota.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ort.txt > ./converted/ort.txt
iconv -f windows-1251 -t UTF-8 ./data/in/otr.txt > ./converted/otr.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ren.txt > ./converted/ren.txt
iconv -f windows-1251 -t UTF-8 ./data/in/retro.txt > ./converted/retro.txt
iconv -f windows-1251 -t UTF-8 ./data/in/ri.txt > ./converted/ri.txt
iconv -f windows-1251 -t UTF-8 ./data/in/rtr.txt > ./converted/rtr.txt
iconv -f windows-1251 -t UTF-8 ./data/in/rtv.txt > ./converted/rtv.txt
iconv -f windows-1251 -t UTF-8 ./data/in/spas.txt > ./converted/spas.txt
iconv -f windows-1251 -t UTF-8 ./data/in/sts.txt > ./converted/sts.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tdk.txt > ./converted/tdk.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tnt.txt > ./converted/tnt.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tv1000.txt > ./converted/tv1000.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tv1000rk.txt > ./converted/tv1000rk.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tv21.txt > ./converted/tv21.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tv3.txt > ./converted/tv3.txt
iconv -f windows-1251 -t UTF-8 ./data/in/tvc.txt > ./converted/tvc.txt
iconv -f windows-1251 -t UTF-8 ./data/in/u.txt > ./converted/u.txt
iconv -f windows-1251 -t UTF-8 ./data/in/usadba.txt > ./converted/usadba.txt
iconv -f windows-1251 -t UTF-8 ./data/in/zdtv.txt > ./converted/zdtv.txt
iconv -f windows-1251 -t UTF-8 ./data/in/zvezda.txt > ./converted/zvezda.txt
